### ISSUE TITLE
More pathways and databases?

### ISSUE THREAD

**Issue by ryanhchung** [guokai8/scGSVA#13]
Hi,

Thanks for developing an amazing package

I was wondering whether we can use databases other than KEGG, also pathways other than wnt signaling pathways.

Thank you!

**Comment by guokai8** [comment]
Hi @ryanhchung ,
Please see the https://github.com/guokai8/scGSVA/issues/7
Best,
K

**Comment by ryanhchung** [comment]
@guokai8 Thanks!
